In [ ]:
#feature_selection_embedded_methods
  #LASSO
  #tree-based feature importance

In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

data = load_breast_cancer()

x = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = pd.Series(data.target)

x.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [2]:
#Lasso
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

lasso = Lasso (alpha = 0.01)

lasso.fit(x_scaled , y)

importance = pd.DataFrame ({
    "Feature": x.columns ,
    "weight": lasso.coef_
})

importance

                    Feature    weight
0               mean radius -0.000000
1              mean texture -0.019530
2            mean perimeter -0.000000
3                 mean area -0.000000
4           mean smoothness -0.000000
5          mean compactness  0.000000
6            mean concavity -0.000000
7       mean concave points -0.045709
8             mean symmetry -0.000000
9    mean fractal dimension  0.015021
10             radius error -0.018349
11            texture error -0.000000
12          perimeter error -0.000000
13               area error  0.000000
14         smoothness error -0.009790
15        compactness error  0.000000
16          concavity error  0.003305
17     concave points error -0.000000
18           symmetry error -0.000000
19  fractal dimension error  0.000000
20             worst radius -0.166596
21            worst texture -0.051017
22          worst perimeter -0.000000
23               worst area -0.000000
24         worst smoothness -0.032805
25        worst compactness -0.000000
26          worst concavity -0.008220
27     worst concave points -0.126911
28           worst symmetry -0.040223
29  worst fractal dimension -0.000000

In [3]:
#
important_features = importance[importance.weight != 0]

important_features

                   Feature    weight
1             mean texture -0.019530
7      mean concave points -0.045709
9   mean fractal dimension  0.015021
10            radius error -0.018349
14        smoothness error -0.009790
16         concavity error  0.003305
20            worst radius -0.166596
21           worst texture -0.051017
24        worst smoothness -0.032805
26         worst concavity -0.008220
27    worst concave points -0.126911
28          worst symmetry -0.040223

In [4]:
# Tree based features
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state = 42).fit( x , y)

importance = pd.DataFrame (
    {

        "Feature": x.columns,
        "Importance": rf.feature_importances_
    }
    )

importance.sort_values(
    by="Importance",
    ascending=False
)

                    Feature  Importance
23               worst area    0.139357
27     worst concave points    0.132225
7       mean concave points    0.107046
20             worst radius    0.082848
22          worst perimeter    0.080850
2            mean perimeter    0.067990
6            mean concavity    0.066917
3                 mean area    0.060462
26          worst concavity    0.037339
0               mean radius    0.034843
13               area error    0.029553
25        worst compactness    0.019864
21            worst texture    0.017485
1              mean texture    0.015225
10             radius error    0.014264
24         worst smoothness    0.012232
5          mean compactness    0.011597
12          perimeter error    0.010085
28           worst symmetry    0.008179
4           mean smoothness    0.007958
19  fractal dimension error    0.005942
16          concavity error    0.005820
15        compactness error    0.005612
14         smoothness error    0.004722
29  worst fractal dimension    0.004497
17     concave points error    0.003760
11            texture error    0.003744
18           symmetry error    0.003546
8             mean symmetry    0.003423
9    mean fractal dimension    0.002615